//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_table
    {
        public int productId { get; set; }
        public string product_name { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> categoryID { get; set; }
    }
}
